[book]
authors = ["Juan Grados", "Michel Langhammer", "J.C. Mariscal-Melgar"]
language = "en"
multilingual = false
src = "src"
title = "OpenLab Microfactory Wiki"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
git-repository-url = "https://github.com/new-production-institute/openlab-microfactory-wiki"
edit-url-template = "https://github.com/new-production-institute/openlab-microfactory-wiki/edit/main/{path}"

[output.html.fold]
enable = true
level = 0
