[book]
authors = ["J.C. Mariscal-Melgar", "Juan Grados"]
language = "en"
multilingual = false
src = "src"
title = "OpenLab Microfactory Wiki"
[output.html]
default-theme = "light"
smart-punctuation = true
git-repository-url = "https://github.com/new-production-institute/openlab-microfactory-wiki"
edit-url-template = "https://github.com/new-production-institute/openlab-microfactory-wiki/edit/main/{path}"


